server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/ec
    username: postgres
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/**/**.xml
  configuration:
    map-underscore-to-camel-case: true
